from django.core.exceptions import ValidationError

def validate_unique_user_article(like):
    pass